TebLocalPlannerROS:

  odom_topic: odometry/filtered
  map_frame: map

  # Robot
  max_vel_x: 0.6
  min_vel_x: 0.05
  max_vel_theta: 1.0
  acc_lim_x: 0.8
  acc_lim_theta: 1.0

  footprint_model:
    type: "polygon"
    vertices: [[-0.21, -0.165], [-0.21, 0.165], [0.21, 0.165], [0.21, -0.165]]

  # Goal tolerances
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.2
  free_goal_vel: false

  # Trajectory
  teb_autosize: true
  dt_ref: 0.3
  dt_hysteresis: 0.1
  max_samples: 500
  global_plan_overwrite_orientation: true
  global_plan_viapoint_sep: 0.3
  weight_optimaltime: 1.0
  weight_obstacle: 100.0
  weight_viapoint: 1.0
  weight_shortest_path: 0.0

  # Obstacles
  min_obstacle_dist: 0.3
  inflation_dist: 0.4
  include_costmap_obstacles: true
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 30

  # Optimization
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: true
  optimization_verbose: false
